title: Deniz Qian

# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    sass_dir: _sass
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Projects
      url: /projects
    - title: Research
      url: /research


social:
    github: dq2024
    email: denizqian@gmail.com
    linkedin: denizqian

google_analytics: "UA-58263416-1"

disqus:
    shortname: denizqian
